CREATE DATABASE ConnectPlus00;
GO

CREATE TABLE TipoDeContato(
TipoDeContatoID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Titulo VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Contato(
IdContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Nome VARCHAR(100) NOT NULL,
formadecontato VARCHAR(256) UNIQUE NOT NULL,
imagem VARCHAR(100) NOT NULL,
tipodecontato VARCHAR(256) UNIQUE NOT NULL,
IdTipoDeContato UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoDeContato(TipoDeContatoID)
);
GO
